name: "Test Tracker"
description: "GitHub action to track test results and metadata in Pull Requests"
author: "kirinnee"
inputs:
  data:
    required: true
    description: "Test Data to Persist. Should be Array of [Input](#input-schema)"
    default: "[]"
  gist_id:
    required: true
    description: "Gist ID to use as persistent store"
  github_token:
    required: true
    description: "GitHub action token with Gist Permission"
  prefix:
    required: false
    description: "Prefix for Key Storage"
  sha:
    required: false
    description: "Use this SHA instead of commit SHA"
  url:
    required: false
    description: "Use this as the repository URL instead of auto-detection"
outputs:
  current:
    description: >-
      The current commit's history entry. Type of [HistoryEntry](#history-entry-schema)
  before:
    description: >-
      The whole history of this PR, excluding this commit. Null if not a PR.
      Type of [HistoryEntry](#history-entry-schema)
  after:
    description: >-
      The whole history of this PR, including this commit. Null if not a PR.
      Type of [HistoryEntry](#history-entry-schema)
  base:
    description: >-
      The history entry of the a base commit of the PR.
      Null if not PR or if base commit has nothing stored.
      Type of [HistoryEntry](#history-entry-schema)
runs:
  using: "node16"
  main: "dist/index.js"
